### ISSUE TITLE
The contents of benchmarkWM2.4 and its help file are mismatched.

### ISSUE THREAD

**Issue by bknakker** [joschadutli/BenchmarksWM#1]
The contents of benchmarkWM2.4 and its help file are mismatched.
Thanks for the great package!

library(BenchmarksWM)
op=capture.output({
benchmarkWM2.4
})

print(op)
#> [1] "        dataset              manipulation  response.variable" 
#> [2] "1      floden10 filled retention interval proportion correct" 
#> [3] "2 lewandowsky10   inter-stimulus interval proportion correct" 
#> [4] "3      ricker17     presentation duration     response error" 
#> [5] "                     task   memory.test     stimulus.material"
#> [6] "1          Brown-Peterson        recall        verbal (words)"
#> [7] "2            complex span        recall                verbal"
#> [8] "3 continuous reproduction serial recall visual (orientations)"
helpstr=help('benchmarkWM2.4')
tools::Rd2txt(utils:::.getHelpFile(as.character(helpstr)))
#> _W_o_r_k_i_n_g _M_e_m_o_r_y _B_e_n_c_h_m_a_r_k_s: _E_f_f_e_c_t_s _o_f _P_r_e_s_e_n_t_a_t_i_o_n _D_u_r_a_t_i_o_n
#> 
#> _D_e_s_c_r_i_p_t_i_o_n:
#> 
#>      Summary dataset relating to the subsection of the Working Memory
#>      Benchmarks datasets (Oberauer, 2019) associated with the effects
#>      of presentation duration. Overall, longer presentation times
#>      increase the probability and/or precision of recall. See section
#>      "Details" for links to the documentation files providing more
#>      precise descriptions of the single datasets included in this
#>      Benchmark.
#> 
#> _D_e_t_a_i_l_s:
#> 
#>      *4 datasets with effects of presentation duration.*
#> 
#>      'tan08' Effects of presentation duration on memory performance in
#>           verbal WM.
#> 
#>      'bays11' Effects of presentation duration on memory performance in
#>           visual WM.
#> 
#>      'grenfell13' Effects of presentation duration on memory
#>           performance in verbal WM with and without articulatory
#>           suppression.
#> 
#>      'ricker17' Effects of presentation duration on memory performance
#>           in visual WM controlling for serial position.
#> 
#> _S_o_u_r_c_e:
#> 
#>      Oberauer, K. (2019). BenchmarksWM.
#>      https://github.com/oberauer/BenchmarksWM
#> 
#> _R_e_f_e_r_e_n_c_e_s:
#> 
#>      Bays, P. M., Gorgoraptis, N., Wee, N., Marshall, L., & Husain, M.
#>      (2011).  Temporal dynamics of encoding, storage, and reallocation
#>      of visual working memory. _Journal of Vision, 11_, 1-15.
#>      http://dx.doi.org/10.1167/11.10.6
#> 
#>      Grenfell-Essam, R., Ward, G., Tan, L. (2013). The Role of
#>      Rehearsal on the Output Order of Immediate Free Recall of Short
#>      and Long Lists.  _Journal of Experimental Psychology: Learning,
#>      Memory, and Cognition, 39_, 317-347.
#>      http://dx.doi.org/10.1037/a0028974
#> 
#>      Oberauer, K., Lewandowsky, S., Awh, E., Brown, G.D.A, Conway, A.,
#>      Cowan, N., Donkin, C., Farrell, S., Hitch, G.J., Hurlstone, M.J.,
#>      Ma, W.J., Morey, C.C., Nee, D.E., Schweppe, J., Vergauwe, E., and
#>      Ward, G. (2018). Benchmarks for models of short-term and working
#>      memory. _Psychological Bulletin, 144_, 885-958.
#> 
#>      Ricker, T. J., Hardman, K. O. (2017). The Nature of Short-Term
#>      Consolidation in Visual Working Memory. _Journal of Experimental
#>      Psychology: General, 146, 11_, 1551-1573.
#>      http://dx.doi.org/10.1037/xge0000346
#> 
#>      Tan, L., & Ward, G. (2008). Rehearsal in immediate serial recall.
#>      _Psychonomic Bulletin & Review, 15_, 535-542.
#>      http://dx.doi.org/10.3758/PBR.15.3.535
#> 
#> _E_x_a_m_p_l_e_s:
#> 
#>      data(ricker17)
#>      ?bays11
#>

**Comment by joschadutli** [comment]
Oh, you are right! Thanks for checking it. Will fix it asap!
